cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path("", views.view_cart, name="view-cart"),
    path("add/<int:item_id>", views.add_to_cart, name="add-to-cart"),
    path("modify/<int:item_id>", views.cart_modify, name="cart-modify"),
    path("delete/<int:item_id>", views.cart_delete, name="cart-delete")
]

project_webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("webshop.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from cart.funcs import get_cart
from webshop.models import Item

# Create your views here.


def add_to_cart(request, item_id):
    cart = request.session.get('cart', {})
    db_item = Item.objects.get(pk=item_id)
    if str(item_id) in cart:
        if cart[str(item_id)] < db_item.quantity:
            cart[str(item_id)] += 1
        else:
            messages.error(request, "На складе недостаточное количество товара, в вашей корзине находится максимум")
    else:
        cart[str(item_id)] = 1
    request.session['cart'] = cart
    return redirect('cart:view-cart')


def view_cart(request):
    items_list, total = get_cart(request)
    return render(request, "cart.html", {"items": items_list, "total": total})


def cart_modify(request, item_id):
    new_quantity = request.POST.get('desired_quantity')
    cart = request.session.get('cart', {})
    cart[str(item_id)] = int(new_quantity)
    request.session['cart'] = cart
    return redirect('cart:view-cart')


def cart_delete(request, item_id):
    cart = request.session.get('cart', {})
    del cart[str(item_id)]
    request.session['cart'] = cart
    return redirect('cart:view-cart')

cart/templates/cart.html
{% extends "base.html" %}

{% block title %}
Корзина
{% endblock %}

{% block content %}
<br>
<h1>Ваша корзина</h1>
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning" role="alert">
{{ message }}
</div>
{% endfor %}
{% endif %}
<table class="table">
    <thead>
<tr>
    <th scope="col">#</th>
  <th scope="col">Название</th>
    <th scope="col">Количество</th>
    <th scope="col">Цена</th>
    <th scope="col">Итого</th>
  <th scope="col">Изменить количество</th>
    <th scope="col"></th>
      <th scope="col">Удалить</th>
</tr>
</thead>
{% for item in items %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
<td><a href="{% url 'item' item.id %}">{{ item.name }}</a></td>
    <td>{{ item.quantity }}</td>
    <td>{{ item.price|floatformat:-2 }}</td>
        <td>{{ item.value|floatformat:-2 }}</td>
    <td>
        <form action="{% url 'cart:cart-modify' item.id %}" method="post">
    {% csrf_token %}
        <input type="range" class="form-range" min="1" max="{{ item.inventory }}" value="{{ item.quantity }}" name="desired_quantity">
    </td>
    <td>
        <button type="submit" class="btn btn-success">Изменить кол-во</button>
        </form>
    </td>
        <td><a href="{% url 'cart:cart-delete' item.id %}">Удалить</a></td>
    </tr>
{% endfor %}
</table>
<h2>Итого стоимость вашей покупки: {{ total|floatformat:-2 }} руб.</h2>
<a href="{% url 'checkout' %}" class="btn btn-primary btn-lg">Оформить заказ</a>
{% endblock %}