cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path("", views.view_cart, name="view-cart"),
    path("add/<int:item_id>", views.add_to_cart, name="add-to-cart"),
    path("modify/<int:item_id>", views.cart_modify, name="cart-modify"),
    path("delete/<int:item_id>", views.cart_delete, name="cart-delete")
]

project_webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("webshop.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.decorators import user_passes_test

urlpatterns = [
    path("", views.index, name="home"),

    path("add-category", views.add_category, name="add-category"),
    path("add-item", views.add_item, name="add-item"),
    path("item/edit/<int:pk>", user_passes_test(lambda user: user.groups.filter(name="moderators").exists(),
                                                login_url=reverse_lazy("denied"))(views.ItemUpdateView.as_view()),
         name="item-edit"),
    path("item/delete/<int:pk>", user_passes_test(lambda user: user.groups.filter(name="moderators").exists(),
                                                  login_url=reverse_lazy("denied"))(views.ItemDeleteView.as_view()),
         name="item-delete"),
    path("category/<slug:category_slug>/order=<str:ordering>", views.category, name="category"),
    path("category/modify", views.category_modify, name="category-modify"),
    path("item/<int:item_id>", views.item_full, name="item"),
    path("search", views.search, name="search"),
    path("checkout", views.checkout, name="checkout"),
    path("checkout/address/old", views.checkout_old_address, name="checkout-address-old"),
    path("checkout/address/new", views.checkout_new_address, name="checkout-address-new"),
    path("orders/manage/sort=<str:sorting>", views.orders_manage, name="orders-manage"),
    path("orders/change/<int:order_id>", views.orders_change, name="orders-change"),
    path("orders/delete/<int:order_id>", views.orders_delete, name="orders-delete"),
    path("orders/order/<int:order_id>/delete_item/<int:item_id>", views.orders_item_delete, name="orders-item-delete"),
    path("orders/add/<int:item_id>", views.orders_item_add, name="orders-item-add"),
    path("orders/edit/address/<int:pk>", views.AddressUpdateView.as_view(), name="orders-edit-address"),
    path("orders/my", views.orders_my, name="orders-my"),
    path("orders/confirm", views.orders_confirm, name="orders-confirm"),
    path("denied", views.denied, name="denied"),
    path("promo/add", views.add_promo, name="promo-add")
]

webshop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="uploads", null=True, blank=True)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="items")
    quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField()
    orders = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Address(models.Model):
    name = models.CharField(max_length=50, verbose_name="Ваше имя")
    phone = models.CharField(max_length=50, verbose_name="Ваш телефон")
    email = models.EmailField(verbose_name="Ваш e-mail")
    city = models.CharField(max_length=50, verbose_name="Город", null=True, blank=True)
    address = models.CharField(max_length=200, verbose_name="Полный адрес", null=True, blank=True)
    comments = models.CharField(max_length=200, verbose_name="Комментарий", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="address")

    def __str__(self):
        return f"{self.phone} - {self.city} - {self.address}"


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.item.name} x{self.quantity}"


DELIVERY_CHOICES = [
    ("selfpick", "самовывоз, бесплатно"),
    ("courier", "доставка курьером, 300 руб."),
    ("post", "доставка почтой, 300 руб.")
]

PAYMENT_CHOICES = [
    ("cash", "наличными при получении"),
    ("online", "банковской картой онлайн"),
    ("card", "банковской картой при получении")
]

STATUS_CHOICES = [
    ("process", "в обработке"),
    ("confirmed", "подтвержден"),
    ("delivery", "доставляется"),
    ("finished", "завершен")
]


class Order(models.Model):
    items = models.ManyToManyField(OrderItem)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    delivery = models.CharField(max_length=20, choices=DELIVERY_CHOICES, null=True, blank=True, verbose_name="Доставка")
    payment = models.CharField(max_length=20, choices=PAYMENT_CHOICES, null=True, blank=True, verbose_name="Оплата")
    total = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="process", verbose_name="Статус заказа")
    promo = models.FloatField(default=1)

    def __str__(self):
        return f"{self.id}"


class Promo(models.Model):
    name = models.CharField(max_length=30)
    expire_date = models.DateField()
    discount = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(100)])

    @property
    def discount_price(self):
        return (100 - self.discount) / 100

    def __str__(self):
        return f"{self.name} - {self.expire_date}"

webshop/forms.py
from django import forms
from django.forms import ModelForm
from .models import Category, Item, Order, Address, Promo


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'slug']


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'title', 'image', 'description', 'category', 'quantity', 'price']


class StatusForm(ModelForm):
    class Meta:
        model = Order
        fields = ['status']


class RegisteredAddressForm(ModelForm):

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].queryset = Address.objects.filter(user=user)

    class Meta:
        model = Order
        fields = ['address']


class PromocodeForm(forms.Form):
    promocode = forms.CharField(max_length=20)


class OrderAddItemForm(forms.Form):
    order = forms.ModelChoiceField(queryset=Order.objects.filter(status="process"))
    quantity = forms.IntegerField(min_value=1)


class PromoForm(ModelForm):
    class Meta:
        model = Promo
        fields = ['name', 'expire_date', 'discount']
        help_texts = {
            'expire_date': 'Введите дату окончания акции в формате дд-мм-гггг',
            'discount': 'Введите скидку в %, целое число'
        }

webshop/views.py
from django.shortcuts import render, redirect, Http404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic.edit import UpdateView, DeleteView
from django.forms import modelform_factory, modelformset_factory
from .forms import CategoryForm, ItemForm, StatusForm, RegisteredAddressForm, PromocodeForm, OrderAddItemForm, PromoForm
from .funcs import check_promo, checkout_save_order, order_manage_items, send_confirmation_mail
from .models import Category, Item, Address, Order, OrderItem, Promo
from cart.funcs import get_cart, get_promo, clear_cart
from django.contrib.auth.decorators import user_passes_test
from datetime import date


# Create your views here.


def index(request):
    popular = Item.objects.order_by("-orders")[:3]
    last = Item.objects.order_by("quantity")[:3]
    return render(request, "index.html", {"popular": popular, "last": last})


@user_passes_test(lambda user: user.groups.filter(name="moderators").exists(), login_url=reverse_lazy("denied"))
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CategoryForm()
    return render(request, 'form.html', {"form": form, "title": "Добавить категорию"})


def category(request, category_slug, ordering):
    selected_category = Category.objects.get(slug=category_slug)
    if ordering == "popular":
        items = selected_category.items.order_by("-orders")
    elif ordering == "name":
        items = selected_category.items.order_by("name")
    elif ordering == "price-lowest":
        items = selected_category.items.order_by("price")
    elif ordering == "price-highest":
        items = selected_category.items.order_by("-price")
    else:
        raise Http404
    return render(request, "category.html", {'category': selected_category, "items": items})


@user_passes_test(lambda user: user.groups.filter(name="moderators").exists(), login_url=reverse_lazy("denied"))
def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('category', category_slug=form.cleaned_data["category"].slug, ordering="popular")
    else:
        form = ItemForm()
    return render(request, 'form.html', {"form": form, "title": "Добавить позицию"})


class ItemUpdateView(UpdateView):
    model = Item
    fields = ['name', 'title', 'image', 'description', 'category', 'quantity', 'price']
    template_name_suffix = '_update'

    def get_success_url(self):
        slug = self.object.category.slug
        return reverse("category", kwargs={"category_slug": slug, "ordering": "popular"})


class ItemDeleteView(DeleteView):
    model = Item

    def get_success_url(self):
        slug = self.object.category.slug
        return reverse("category", kwargs={"category_slug": slug, "ordering": "popular"})


def item_full(request, item_id):
    selected_item = Item.objects.get(pk=item_id)
    return render(request, 'item.html', {"item": selected_item})


def search(request):
    search_query = request.POST["search_input"]
    items_case = Item.objects.filter(name__contains=search_query)
    items_non_case = Item.objects.filter(name__contains=search_query.title())
    items = items_case.union(items_non_case)
    return render(request, "search.html", {"items": items})


def checkout(request):
    if request.method == "POST":
        form = PromocodeForm(request.POST)
        if form.is_valid():
            promocode = form.cleaned_data["promocode"]
            try:
                request.session['promocode'] = None
                db_promo = Promo.objects.get(name=promocode)
                if db_promo.expire_date > date.today():
                    request.session['promocode'] = db_promo.name
                    return redirect('checkout')
                else:
                    messages.error(request, "Промокод устарел. Попробуйте другой или продолжите без промокода")
            except Promo.DoesNotExist:
                messages.error(request,
                               "Вы ввели недействительный промокод. Попробуйте еще раз или продолжите без промокода")

    else:
        form = PromocodeForm()

    items, total = get_cart(request)
    promo = check_promo(get_promo(request))
    for item in items:
        if item["quantity"] > item["inventory"]:
            cart = request.session["cart"]
            cart[str(item["id"])] = item["inventory"]
            request.session["cart"] = cart
            messages.error(request, f"Количество товара {item['name']} было скорректировано")
            return redirect("checkout")

    return render(request, "checkout.html", {"items": items, "total": total, "form": form, "promo": promo})


def checkout_old_address(request):
    items, total = get_cart(request)
    promo = check_promo(get_promo(request))

    if request.method == "POST":
        form_address = RegisteredAddressForm(request.POST, user=request.user)
        if form_address.is_valid():
            address = form_address.cleaned_data["address"]
        form_choices = modelform_factory(Order, fields=["delivery", "payment"])(request.POST)
        order = checkout_save_order(request, form_choices, address)
        order_manage_items(request, order)
        clear_cart(request)
        send_confirmation_mail(order)
        messages.success(request,
                         f"Заказ #{order.id} успешно создан. Дождитесь звонка оператора для подтверждения заказа")
        return redirect("orders-confirm")

    else:
        form_address = RegisteredAddressForm(user=request.user)
        form_choices = modelform_factory(Order, fields=["delivery", "payment"])

    return render(request, "checkout-address.html", {"items": items, "total": total, "promo": promo,
                                                     "form1": form_address,
                                                     "form2": form_choices,
                                                     "address": 'old'})


def checkout_new_address(request):
    items, total = get_cart(request)
    promo = check_promo(get_promo(request))

    if request.method == "POST":
        form_address = modelform_factory(Address, exclude=["user"])(request.POST)
        if form_address.is_valid():
            address = form_address.save(commit=False)
            if request.user.is_authenticated:
                address.user = request.user
            address.save()
        form_choices = modelform_factory(Order, fields=["delivery", "payment"])(request.POST)
        order = checkout_save_order(request, form_choices, address)
        order_manage_items(request, order)
        clear_cart(request)
        send_confirmation_mail(order)
        messages.success(request,
                         f"Заказ #{order.id} успешно создан. Дождитесь звонка оператора для подтверждения заказа")
        return redirect("orders-confirm")

    else:
        form_address = modelform_factory(Address, exclude=["user"])
        form_choices = modelform_factory(Order, fields=["delivery", "payment"])

    return render(request, "checkout-address.html", {"items": items, "total": total, "promo": promo,
                                                     "form1": form_address,
                                                     "form2": form_choices,
                                                     "address": 'new'})


@user_passes_test(lambda user: user.groups.filter(name="moderators").exists(), login_url=reverse_lazy("denied"))
def orders_manage(request, sorting):
    optimized_orders = Order.objects.select_related('address').prefetch_related('items').prefetch_related('items__item')
    if sorting == "all":
        orders = optimized_orders.order_by("-id")
    elif sorting == "process":
        orders = optimized_orders.filter(status="process").order_by("-id")
    elif sorting == "confirmed":
        orders = optimized_orders.filter(status="confirmed").order_by("-id")
    elif sorting == "delivery":
        orders = optimized_orders.filter(status="delivery").order_by("-id")
    elif sorting == "finished":
        orders = optimized_orders.filter(status="finished").order_by("-id")
    elif sorting == "last":
        orders = optimized_orders.order_by("-id")[:10]
    else:
        raise Http404
    form = StatusForm()
    return render(request, "orders.html", {"all_orders": orders, "form": form})


@user_passes_test(lambda user: user.groups.filter(name="moderators").exists(), login_url=reverse_lazy("denied"))
def orders_change(request, order_id):
    form = StatusForm(request.POST)
    if form.is_valid():
        order = Order.objects.get(id=order_id)
        order.status = form.cleaned_data["status"]
        order.save()
    return redirect("orders-manage", sorting="all")


def orders_delete(request, order_id):
    order = Order.objects.get(id=order_id)
    order_items = order.items.all().select_related('item')
    items_list = [item.item for item in order_items]
    quantity_list = [item.quantity for item in order_items]
    for item, quantity in zip(items_list, quantity_list):
        item.quantity += quantity
        item.orders -= 1
    Item.objects.bulk_update(items_list, ['quantity', 'orders'])
    order.delete()
    if request.user.groups.filter(name="moderators").exists():
        return redirect("orders-manage", sorting="all")
    else:
        return redirect("orders-my")


@user_passes_test(lambda user: user.groups.filter(name="moderators").exists(), login_url=reverse_lazy("denied"))
def orders_item_delete(request, order_id, item_id):
    order = Order.objects.get(id=order_id)
    item = OrderItem.objects.get(id=item_id)
    item.item.quantity += item.quantity
    item.item.orders -= 1
    item.item.save()
    order.items.remove(item)
    order.total -= order.promo * item.item.price * item.quantity
    order.save()

webshop/templates/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Добавить позицию
{% endblock %}

{% block content %}
<h2>Добавить позицию</h2>
  <form enctype='multipart/form-data' method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Добавить</button>
  </form>
{% endblock %}

webshop/templates/base.html
<!--{% load is_moderator %}-->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-xl">
    <a class="navbar-brand" href="#">Webshop</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Категории
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in categories %}
            <li><a class="dropdown-item" href="{% url 'category' category.slug 'popular' %}">{{ category.name }}</a></li>
            {% endfor %}
              {% if moderator %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'add-category' %}">Добавить категорию</a></li>
              <li><a class="dropdown-item" href="{% url 'category-modify' %}">Изменить категории</a></li>
               <li><a class="dropdown-item" href="{% url 'promo-add' %}">Добавить промокод</a></li>
              {% endif %}
          </ul>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">О магазине</a>
        </li>

      </ul>
      <form class="d-flex" role="search" action="{% url 'search' %}" method="post">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_input">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'cart:view-cart' %}">В корзине: {{ cart_length }} позиции</a>
            </li>
            {% if moderator %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'orders-manage' 'all' %}">Менеджер заказов</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'orders-my' %}">Мои заказы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'change-password' %}">Сменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "logout" %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "login" %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "signup" %}">Регистрация</a>
            </li>
            {% endif %}
        </ul>
    </div>
  </div>
</nav>

<body>
    <div class="container-xl">
    {% block content %}
    {% endblock %}
    </div>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

webshop/templates/card-item.html
<div class="card h-100" style="width: 16rem;">
  <img src="{{ item.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ item.name }}</h5>
    <p class="card-text">{{ item.title }}</p>
    <span>Цена: {{ item.price|floatformat:-2 }} руб.</span>
    {% if item.quantity == 0 %}
    <br>
    <small>Товара нет в наличии</small>
    {% endif %}
    <br>
    {% if item.quantity > 0 %}
    <a href="{% url 'item' item.id %}" class="btn btn-primary">Подробнее</a>
    <a href="{% url 'cart:add-to-cart' item.id %}" class="btn btn-primary">В корзину</a>
    {% else %}
    {% if moderator %}
    <a href="{% url 'item' item.id %}" class="btn btn-primary">Подробнее</a>
    <a  class="btn btn-primary disabled" aria-disabled="true">В корзину</a>
    {% else %}
    <a  class="btn btn-primary disabled" aria-disabled="true">Подробнее</a>
    <a  class="btn btn-primary disabled" aria-disabled="true">В корзину</a>
    {% endif %}
    {% endif %}
  </div>
</div>

webshop/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<h2>{{ title }}</h2>
  <form enctype='multipart/form-data' method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Добавить</button>
  </form>
{% endblock %}

webshop/templates/item.html
{% extends "base.html" %}

{% block title %}
{{ item.name }}
{% endblock %}

{% block content %}
<h2>{{ item.name }}</h2>
<img src="{{ item.image.url }}" width="300">
<p>{{ item.description }}</p>
<span>На складе: {{ item.quantity }}</span>
<h4>Цена: {{ item.price|floatformat:-2 }} руб.</h4>
{% if item.quantity > 0 %}
<a href="{% url 'cart:add-to-cart' item.id %}" class="btn btn-primary">В корзину</a>
{% else %}
<a  class="btn btn-primary disabled" aria-disabled="true">В корзину</a>
{% endif %}
{% if moderator %}
<a href="{% url "item-edit" item.id %}" class="btn btn-success">Изменить</a>
<a href="{% url "item-delete" item.id %}" class="btn btn-danger">Удалить</a>
{% if item.quantity > 0 %}
<a href="{% url "orders-item-add" item.id %}" class="btn btn-danger">Добавить в заказ</a>
{% endif %}
{% endif %}

{% endblock %}

webshop/templates/orders.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Администрирование заказов
{% endblock %}

{% block content %}
<h2>Администрирование заказов</h2>
<ul class="nav">
  <li class="nav-item">
    <span class="nav-link disabled" >Сортировка: </span>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'all' %}">Все</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'process' %}">В обработке</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'confirmed' %}">Подтвержден</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'delivery' %}">Доставляется</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'finished' %}">Завершен</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'orders-manage' 'last' %}">Последние 10</a>
  </li>
</ul>
<br>
<div class="accordion" id="accordionExample">
{% for order in all_orders %}

  <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ forloop.counter }}">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
        Заказ #{{ order.id }} на сумму {{ order.total }} руб: {{ order.get_status_display }}
      </button>
    </h2>
    <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          <p>Имя: {{ order.address.name }}, телефон: {{ order.address.phone }}</p>
          <table class="table">
       {% for item in order.items.all %}
              <tr>
        <td><a href="{% url 'item' item.item.id %}">{{ item.item.name }}</a></td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.item.price }} руб</td>
                  <td><a href="{% url 'orders-item-delete' order.id item.id %}">Удалить позицию</a></td>
              </tr>
          {% endfor %}
              </table>
   <br>
          <span>Доставка: {{ order.get_delivery_display }}</span>
          <br>
          <span>Оплата: {{ order.get_payment_display }}</span>
          <br>
        <span>Адрес: {{order.address.city}}, {{ order.address.address }}</span>
           <form action="{% url 'orders-change' order.id %}" method="post">
    {% csrf_token %}
               {{ form|crispy }}
    <button type="submit" class="btn btn-success">Изменить статус заказа</button>
  </form>
          <br>
          <a href="{% url 'orders-edit-address' order.address.id %}" class="btn btn-success">Изменить адрес</a>
          <a href="{% url 'orders-delete' order.id %}" class="btn btn-danger">Отменить заказ</a>
      </div>
    </div>
  </div>


{% endfor %}
    </div>
{% endblock %}

webshop/templates/orders_my.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Мои заказы
{% endblock %}

{% block content %}
<h2>Мои заказы</h2>
{% if not orders %}
<div class="alert alert-success" role="alert">
  У вас пока нет заказов. Поспешите и сделайте один!
</div>
{% endif %}
<div class="accordion" id="accordionExample">
{% for order in orders %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ forloop.counter }}">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
        Заказ #{{ order.id }} на сумму {{ order.total }} руб: {{ order.get_status_display }}
      </button>
    </h2>
    <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          <p>Имя: {{ order.address.name }}, телефон: {{ order.address.phone }}</p>
          <table class="table">
       {% for item in order.items.all %}
              <tr>
        <td><a href="{% url 'item' item.item.id %}">{{ item.item.name }}</a></td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.item.price }} руб</td>
                  <td><a href="{% url 'orders-item-delete' order.id item.id %}">Удалить позицию</a></td>
              </tr>
          {% endfor %}
              </table>
   <br>
          <span>Доставка: {{ order.get_delivery_display }}</span>
          <br>
          <span>Оплата: {{ order.get_payment_display }}</span>
          <br>
        <span>Адрес: {{order.address.city}}, {{ order.address.address }}</span>
          <br>
          <a href="{% url 'orders-edit-address' order.address.id %}" class="btn btn-success">Изменить адрес</a>
          <a href="{% url 'orders-delete' order.id %}" class="btn btn-danger">Отменить заказ</a>
      </div>
    </div>
  </div>
{% endfor %}
    </div>
{% endblock %}